### ISSUE TITLE
Is the control of 'backoff' by 'httpclientutil.RetriableTransport' thread-safe?

### ISSUE THREAD

**Issue by WhiteRaven777** [lufia/httpclientutil#1]
When used like this test code, 'n' (tCount.n) in 'client' looks like a conflict write is suppressed by a mutex lock.
However, since 'client' is a variable defined outside the 'for' loop, it may be able to be manipulated from multiple goroutines.
Therefore, I think that even if you set the maximum number of requests for each request, it won't work in a coordinated manner.

I think that the count-up process of retries in 'backoff' in 'client' may be affected in the same way.

Please give us your interpretation.

https://github.com/lufia/httpclientutil/blob/ebe9ef396ac6e02f62db52f56cbf62e8996b2d26/bench_test.go#L84

**Comment by lufia** [comment]
> However, since 'client' is a variable defined outside the 'for' loop, it may be able to be manipulated from multiple goroutines.

Right. I believe both http.Client and http.Transport are goroutine-safe.

> Therefore, I think that even if you set the maximum number of requests for each request, it won't work in a coordinated manner.

Hmm... I hadn't understood to restrict the maximum number of the requests. Which lines is the above sentence points to?

Sorry, I have forgotten the object of this benchmark. Maybe it was intended to keep the performance equivalent to use http.Transport directly.
Thus I expect the benchmark to: all goroutines created in the benchmark shares one client. Each goroutines will open new connection to the s.URL in the same time as much as it can. Finally, someone checks peak count is small enough if needed.
